local:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: airflow
      pass: airflow
      dbname: airflow
      schema: public
    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "" 
      dbname: postgres
      schema: public
